CONFIG_ZMK_SLEEP=n

# Disable backlight and encoders on the dongle
CONFIG_ZMK_BACKLIGHT=n
CONFIG_EC11=n
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=n

CONFIG_USB=y
# Connectivity settings are handled in Kconfig.defconfig
# to ensure they are the correct defaults for the shield.
